### ISSUE TITLE
API

### ISSUE THREAD

**Issue by OlMi1** [Joohansson/keytools#7]
Hi, this is not really an idea but what about this:

https://tools.nanos.cc/?tool=keygen&count=1&priv=true&pub=true&addr=true

but as an API call? That would mean wallets can be easily generated for testing purposes since there are not a lot of SDKs avaialable.

**Comment by Joohansson** [comment]
You can do that from my other tool:
https://api.nanos.cc
Or GET request directly: https://proxy.nanos.cc/proxy/?action=key_create
